const stockSymbolData = [
  {
    id: 277,
    symbol: 'AATMA',
    name: 'Aatmanirbhar Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 90,
    symbol: 'ACLBSL',
    name: 'Aarambha Chautari Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 21,
    symbol: 'ADBL',
    name: 'Agriculture Development Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 244,
    symbol: 'ADLB',
    name: 'Adarsha Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 270,
    symbol: 'AHL',
    name: 'Asian Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 144,
    symbol: 'AHPC',
    name: 'Arun Valley Hydropower Development Co. Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 138,
    symbol: 'AIL',
    name: 'Ajod Insurance Limited',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 108,
    symbol: 'AKBSL',
    name: 'ADHIKHOLA LAGHUBITTA BITTIYA SANSTHA LIMITED',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 162,
    symbol: 'AKJCL',
    name: 'Ankhu Khola Jalvidhyut Company Ltd',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 152,
    symbol: 'AKPL',
    name: 'Arun Kabeli Power Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 92,
    symbol: 'ALBSL',
    name: 'Asha Laghubitta Bittiya Sanstha Ltd',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 114,
    symbol: 'ALICL',
    name: 'Asian Life Insurance Co. Limited',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 148,
    symbol: 'API',
    name: 'Api Power Company Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 247,
    symbol: 'AVYAN',
    name: 'Aviyan Laghubitta bittiya Sanstha limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 147,
    symbol: 'BARUN',
    name: 'Barun Hydropower Co. Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 200,
    symbol: 'BBC',
    name: 'Bishal Bazar Company Limited',
    sector_id: 12,
    type: 'stock',
  },
  {
    id: 282,
    symbol: 'BEDCL',
    name: 'Bhugol Energy Development Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 47,
    symbol: 'BFC',
    name: 'Best Finance Company Ltd.',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 259,
    symbol: 'BHDC',
    name: 'Bindhyabasini Hydropower Development Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 237,
    symbol: 'BHL',
    name: 'Balephi Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 267,
    symbol: 'BHPL',
    name: 'Barahi Hydropower Public Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 202,
    symbol: 'BNHC',
    name: 'Buddha Bhumi Nepal Hydropower Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 187,
    symbol: 'BNL',
    name: 'Bottlers Nepal (Balaju) Limited',
    sector_id: 8,
    type: 'stock',
  },
  {
    id: 189,
    symbol: 'BNT',
    name: 'Bottlers Nepal (Terai) Limited',
    sector_id: 8,
    type: 'stock',
  },
  {
    id: 7,
    symbol: 'BOKL',
    name: 'Bank of Kathmandu Ltd.',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 142,
    symbol: 'BPCL',
    name: 'Butwal Power Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 275,
    symbol: 'BPW',
    name: 'BPW LAghubitta Bittya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 61,
    symbol: 'CBBL',
    name: 'Chhimek Laghubitta Bikas Bank Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 23,
    symbol: 'CBL',
    name: 'Civil Bank Ltd',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 25,
    symbol: 'CCBL',
    name: 'Century Commercial Bank Ltd.',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 51,
    symbol: 'CFCL',
    name: 'Central Finance Co. Ltd.',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 196,
    symbol: 'CGH',
    name: 'Chandragiri Hills Limited',
    sector_id: 4,
    type: 'stock',
  },
  {
    id: 143,
    symbol: 'CHCL',
    name: 'Chilime Hydropower Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 186,
    symbol: 'CHDC',
    name: 'CEDB Hydropower Development Company Limited',
    sector_id: 6,
    type: 'stock',
  },
  {
    id: 155,
    symbol: 'CHL',
    name: 'Chhyangdi Hydropower Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 182,
    symbol: 'CIT',
    name: 'Citizen Investment Trust',
    sector_id: 6,
    type: 'stock',
  },
  {
    id: 77,
    symbol: 'CLBSL',
    name: 'Civil Laghubitta Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 226,
    symbol: 'CMF1',
    name: 'Citizens Mutual Fund -1',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 223,
    symbol: 'CMF2',
    name: 'CITIZENS MUTUAL FUND 2',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 36,
    symbol: 'CORBL',
    name: 'Corporate Development Bank Limited',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 239,
    symbol: 'CYCL',
    name: 'CYC Nepal Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 18,
    symbol: 'CZBIL',
    name: 'Citizens Bank International Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 62,
    symbol: 'DDBL',
    name: 'Deprosc Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 151,
    symbol: 'DHPL',
    name: 'Dibyashwori Hydropower Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 248,
    symbol: 'DLBS',
    name: 'Dhaulagiri Lahubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 242,
    symbol: 'DORDI',
    name: 'Dordi Khola Hydropower Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 281,
    symbol: 'DPCL',
    name: 'Dolti Power Company Ltd',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 6,
    symbol: 'EBL',
    name: 'Everest Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 29,
    symbol: 'EDBL',
    name: 'Excel Development Bank Ltd.',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 254,
    symbol: 'EHPL',
    name: 'Eastern Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 127,
    symbol: 'EIC',
    name: 'Everest Insurance Co. Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 207,
    symbol: 'ENL',
    name: 'Emerging Nepal Limited',
    sector_id: 6,
    type: 'stock',
  },
  {
    id: 65,
    symbol: 'FMDBL',
    name: 'First Micro Finance Development Bank Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 85,
    symbol: 'FOWAD',
    name: 'Forward Microfinance Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 33,
    symbol: 'GBBL',
    name: 'Garima Bikas Bank Limited',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 17,
    symbol: 'GBIME',
    name: 'Global IME Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 70,
    symbol: 'GBLBS',
    name: 'Grameen Bikas Laghubitta Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 48,
    symbol: 'GFCL',
    name: 'Goodwill Finance Co. Ltd.',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 109,
    symbol: 'GGBSL',
    name: 'Ghodighoda Laghubitta Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 165,
    symbol: 'GHL',
    name: 'Ghalemdi Hydro Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 139,
    symbol: 'GIC',
    name: 'General Insurance Company Nepal Ltd',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 81,
    symbol: 'GILB',
    name: 'Global IME Laghubitta Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 234,
    symbol: 'GIMES1',
    name: 'Global IME Samunnat Scheme-1',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 94,
    symbol: 'GLBSL',
    name: 'Gurans Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 178,
    symbol: 'GLH',
    name: 'GreenLife Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 117,
    symbol: 'GLICL',
    name: 'Gurans Life Insurance Company Ltd.',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 93,
    symbol: 'GMFBS',
    name: 'Ganapati Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 54,
    symbol: 'GMFIL',
    name: 'Guheshowori Merchant Bank & Finance Co. Ltd.',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 42,
    symbol: 'GRDBL',
    name: 'Green Development Bank Ltd.',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 46,
    symbol: 'GUFL',
    name: 'Gurkhas Finance Ltd.',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 236,
    symbol: 'GVL',
    name: 'Green Ventures Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 26,
    symbol: 'HBL',
    name: 'Himalayan Bank Ltd.',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 173,
    symbol: 'HDHPC',
    name: 'Himal Dolakha Hydropower Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 191,
    symbol: 'HDL',
    name: 'Himalayan Distillery Limited',
    sector_id: 8,
    type: 'stock',
  },
  {
    id: 261,
    symbol: 'HEI',
    name: 'Himalayan Everest Insurance Limited',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 125,
    symbol: 'HGI',
    name: 'Himalayan General Insurance Co. Ltd',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 245,
    symbol: 'HHL',
    name: 'Himalayan Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 183,
    symbol: 'HIDCL',
    name: 'Hydorelectricity Investment and Development Company Ltd',
    sector_id: 6,
    type: 'stock',
  },
  {
    id: 156,
    symbol: 'HPPL',
    name: 'Himalayan Power Partner Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 169,
    symbol: 'HURJA',
    name: 'Himalaya Urja Bikas Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 55,
    symbol: 'ICFC',
    name: 'ICFC Finance Limited',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 132,
    symbol: 'IGI',
    name: 'IME General Insurance Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 284,
    symbol: 'IHL',
    name: 'Ingwa Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 96,
    symbol: 'ILBS',
    name: 'Infinity Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 206,
    symbol: 'JALPA',
    name: 'Jalpa Samudayik Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 34,
    symbol: 'JBBL',
    name: 'Jyoti Bikash  Bank Limited',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 101,
    symbol: 'JBLB',
    name: 'Jeevan Bikas Laghubitta Bittya Sanstha Ltd',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 52,
    symbol: 'JFL',
    name: 'Janaki Finance Ltd.',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 120,
    symbol: 'JLI',
    name: 'Jyoti Life Insurance Ltd',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 163,
    symbol: 'JOSHI',
    name: 'Joshi Hydropower Development Company Ltd',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 79,
    symbol: 'JSLBB',
    name: 'Janautthan Samudayic Laghubitta Bikas Bank Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 11,
    symbol: 'KBL',
    name: 'Kumari Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 266,
    symbol: 'KDL',
    name: 'Kalinchowk Darshan Limited',
    sector_id: 4,
    type: 'stock',
  },
  {
    id: 217,
    symbol: 'KEF',
    name: 'Kumari Equity Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 150,
    symbol: 'KKHC',
    name: 'Khanikhola Hydropower Co. Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 255,
    symbol: 'KLBS',
    name: 'Khaptad Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 78,
    symbol: 'KLBSL',
    name: 'Kisan Lagubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 72,
    symbol: 'KMCDB',
    name: 'Kalika Microcredit Development Bank Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 161,
    symbol: 'KPCL',
    name: 'Kalika power Company Ltd',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 35,
    symbol: 'KRBL',
    name: 'Karnali Development Bank Limited',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 37,
    symbol: 'KSBBL',
    name: 'Kamana Sewa Bikas Bank Limited',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 30,
    symbol: 'LBBL',
    name: 'Lumbini Bikas Bank Ltd.',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 10,
    symbol: 'LBL',
    name: 'Laxmi Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 174,
    symbol: 'LEC',
    name: 'Liberty Energy Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 230,
    symbol: 'LEMF',
    name: 'Laxmi Equity Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 134,
    symbol: 'LGIL',
    name: 'Lumbini General Insurance Co. Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 113,
    symbol: 'LICN',
    name: 'Life Insurance Co. Nepal',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 74,
    symbol: 'LLBS',
    name: 'Laxmi Laghubitta Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 219,
    symbol: 'LUK',
    name: 'Laxmi Unnati Kosh',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 274,
    symbol: 'MAKAR',
    name: 'Makar JItumaya Suri Hydropower Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 204,
    symbol: 'MBJC',
    name: 'Madhya Bhotekoshi Jalavidyut Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 9,
    symbol: 'MBL',
    name: 'Machhapuchhre Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 31,
    symbol: 'MDB',
    name: 'Miteri Development Bank Limited',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 24,
    symbol: 'MEGA',
    name: 'Mega Bank Nepal Ltd.',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 176,
    symbol: 'MEN',
    name: 'Mountain Energy Nepal Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 82,
    symbol: 'MERO',
    name: 'Mero Microfinance Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 58,
    symbol: 'MFIL',
    name: 'Manjushree Finance Ltd.',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 283,
    symbol: 'MHCL',
    name: 'Molung Hydropower Power Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 252,
    symbol: 'MHL',
    name: 'Mandakini Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 167,
    symbol: 'MHNL',
    name: 'Mountain Hydro Nepal Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 271,
    symbol: 'MKHC',
    name: 'Maya Khola Hydropower Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 286,
    symbol: 'MKHL',
    name: 'Mai Khola Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 181,
    symbol: 'MKJC',
    name: 'Mailung Khola Jal Vidhyut Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 102,
    symbol: 'MKLB',
    name: 'Manakamana Smart Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 73,
    symbol: 'MLBBL',
    name: 'Mithila LaghuBitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 32,
    symbol: 'MLBL',
    name: 'Mahalaxmi Bikas Bank Ltd.',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 103,
    symbol: 'MLBS',
    name: 'Manushi Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 100,
    symbol: 'MLBSL',
    name: 'Mahila Lagubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 212,
    symbol: 'MMF1',
    name: 'Mega Mutual Fund -1',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 75,
    symbol: 'MMFDB',
    name: 'Mirmire Microfinance Development Bank Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 40,
    symbol: 'MNBBL',
    name: 'Muktinath Bikas Bank Ltd.',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 57,
    symbol: 'MPFL',
    name: 'Multipurpose Finance Company Limited',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 87,
    symbol: 'MSLB',
    name: 'Mahuli Samudayik Laghubitta Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 28,
    symbol: 'NABBC',
    name: 'Narayani Development Bank Limited',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 2,
    symbol: 'NABIL',
    name: 'Nabil Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 106,
    symbol: 'NADEP',
    name: 'Nadep Laghubittiya bittya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 107,
    symbol: 'NAGRO',
    name: 'Nepal Agro Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 5,
    symbol: 'NBB',
    name: 'Nepal Bangladesh Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 225,
    symbol: 'NBF2',
    name: 'NABIL BALANCED FUND-2',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 211,
    symbol: 'NBF3',
    name: 'Nabil Balanced Fund-3',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 22,
    symbol: 'NBL',
    name: 'Nepal Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 12,
    symbol: 'NCCB',
    name: 'Nepal Credit And Commercial Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 232,
    symbol: 'NEF',
    name: 'Nabil Equity Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 241,
    symbol: 'NESDO',
    name: 'NESDO Sambridha Laghubitta Bittiye Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 45,
    symbol: 'NFS',
    name: 'Nepal Finance Ltd.',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 149,
    symbol: 'NGPL',
    name: 'Ngadi Group Power Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 157,
    symbol: 'NHDL',
    name: 'Nepal Hydro Developers Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 141,
    symbol: 'NHPC',
    name: 'National Hydro Power Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 231,
    symbol: 'NIBLPF',
    name: 'NIBL Pragati Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 210,
    symbol: 'NIBSF2',
    name: 'NIBL Samriddhi Fund -2',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 8,
    symbol: 'NICA',
    name: 'NIC Asia Bank Ltd.',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 222,
    symbol: 'NICBF',
    name: 'NIC Asia Balanced Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 264,
    symbol: 'NICFC',
    name: 'NIC Asia Flexi CAP Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 227,
    symbol: 'NICGF',
    name: 'NIC Asia Growth Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 123,
    symbol: 'NICL',
    name: 'Nepal Insurance Co. Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 98,
    symbol: 'NICLBSL',
    name: 'NIC ASIA Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 214,
    symbol: 'NICSF',
    name: 'NIC Asia Select Fund 30',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 185,
    symbol: 'NIFRA',
    name: 'Nepal Infrastructure Bank Limited',
    sector_id: 6,
    type: 'stock',
  },
  {
    id: 129,
    symbol: 'NIL',
    name: 'Neco Insurance Co. Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 27,
    symbol: 'NIMB',
    name: 'Nepal Investment Mega Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 64,
    symbol: 'NLBBL',
    name: 'Nerude Laghubita Bikas Bank Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 137,
    symbol: 'NLG',
    name: 'NLG Insurance Company Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 112,
    symbol: 'NLIC',
    name: 'Nepal Life Insurance Co. Ltd.',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 111,
    symbol: 'NLICL',
    name: 'National Life Insurance Co. Ltd.',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 188,
    symbol: 'NLO',
    name: 'Nepal Lube Oil Limited',
    sector_id: 8,
    type: 'stock',
  },
  {
    id: 15,
    symbol: 'NMB',
    name: 'NMB Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  { id: 221, symbol: 'NMB50', name: 'NMB 50', sector_id: 13, type: 'stock' },
  {
    id: 233,
    symbol: 'NMBHF1',
    name: 'NMB Hybrid Fund L-1',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 80,
    symbol: 'NMBMF',
    name: 'NMB Microfinance Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 83,
    symbol: 'NMFBS',
    name: 'National Microfinance Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 198,
    symbol: 'NRIC',
    name: 'Nepal Reinsurance Company Limited',
    sector_id: 11,
    type: 'stock',
  },
  {
    id: 184,
    symbol: 'NRN',
    name: 'NRN Infrastructure and Development Limited',
    sector_id: 6,
    type: 'stock',
  },
  {
    id: 105,
    symbol: 'NSEWA',
    name: 'Nepal Seva Laghubitta Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 71,
    symbol: 'NSLB',
    name: 'Naya Sarathi Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 197,
    symbol: 'NTC',
    name: 'Nepal Doorsanchar Comapany Limited',
    sector_id: 11,
    type: 'stock',
  },
  {
    id: 60,
    symbol: 'NUBL',
    name: 'Nirdhan Utthan Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 203,
    symbol: 'NYADI',
    name: 'Nyadi Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 195,
    symbol: 'OHL',
    name: 'Oriental Hotels Limited',
    sector_id: 4,
    type: 'stock',
  },
  {
    id: 19,
    symbol: 'PCBL',
    name: 'Prime Commercial Bank Ltd.',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 49,
    symbol: 'PFL',
    name: 'Pokhara Finance Ltd.',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 265,
    symbol: 'PHCL',
    name: 'Peoples Hydropower Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 128,
    symbol: 'PIC',
    name: 'Premier Insurance Co. Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 133,
    symbol: 'PICL',
    name: 'Prudential Insurance Co. Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 119,
    symbol: 'PLI',
    name: 'Prabhu Life Insurance Limited',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 115,
    symbol: 'PLIC',
    name: 'Prime Life Insurance Company Limited',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 160,
    symbol: 'PMHPL',
    name: 'Panchakanya Mai Hydropower Ltd',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 168,
    symbol: 'PPCL',
    name: 'Panchthar Power Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 257,
    symbol: 'PPL',
    name: "People's Power Limited",
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 130,
    symbol: 'PRIN',
    name: 'Prabhu Insurance Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 56,
    symbol: 'PROFL',
    name: 'ProgressiveFinance Limited',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 16,
    symbol: 'PRVU',
    name: 'Prabhu Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 215,
    symbol: 'PSF',
    name: 'Prabhu Select Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 158,
    symbol: 'RADHI',
    name: 'Radhi Bidyut Company Ltd',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 124,
    symbol: 'RBCL',
    name: 'Rastriya Beema Company Limited',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 240,
    symbol: 'RFPL',
    name: 'River Falls Power Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 250,
    symbol: 'RHGCL',
    name: 'Rapti Hydro and General Construction Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 146,
    symbol: 'RHPC',
    name: 'Ridi Hydropower Development Company Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 171,
    symbol: 'RHPL',
    name: 'RASUWAGADHI HYDROPOWER COMPANY LIMITED',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 258,
    symbol: 'RIDI',
    name: 'Ridi Power Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 59,
    symbol: 'RLFL',
    name: 'Reliance Finance Ltd.',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 118,
    symbol: 'RLI',
    name: 'Reliance Life Insurance Limited',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 69,
    symbol: 'RMDC',
    name: 'RMDC Laghubitta Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 213,
    symbol: 'RMF1',
    name: 'RBB Mutual Fund 1',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 159,
    symbol: 'RRHP',
    name: 'Rairang Hydropower Development Company Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 84,
    symbol: 'RSDC',
    name: 'RSDC Laghubitta Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 208,
    symbol: 'RULB',
    name: 'Rastra Utthan Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 180,
    symbol: 'RURU',
    name: 'Ru Ru Jalbidhyut Pariyojana Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 97,
    symbol: 'SABSL',
    name: 'SABAIKO LAGHUBITTA BITTIYA SANSTHA LIMITED',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 38,
    symbol: 'SADBL',
    name: 'Shangrila Development Bank Ltd.',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 228,
    symbol: 'SAEF',
    name: 'Sanima Equity Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 201,
    symbol: 'SAHAS',
    name: 'Sahas Urja Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 110,
    symbol: 'SAMAJ',
    name: 'Samaj Laghubittya Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 14,
    symbol: 'SANIMA',
    name: 'Sanima Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 43,
    symbol: 'SAPDBL',
    name: 'Saptakoshi Development Bank Ltd',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 216,
    symbol: 'SBCF',
    name: 'Sunrise Bluechip Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 4,
    symbol: 'SBI',
    name: 'Nepal SBI Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 13,
    symbol: 'SBL',
    name: 'Siddhartha Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 3,
    symbol: 'SCB',
    name: 'Standard Chartered Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 99,
    symbol: 'SDLBSL',
    name: 'Sadhana Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 229,
    symbol: 'SEF',
    name: 'Siddhartha Equity Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 53,
    symbol: 'SFCL',
    name: 'Samriddhi Finance Company Limited',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 220,
    symbol: 'SFMF',
    name: 'Sunrise First Mutual Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 249,
    symbol: 'SGHC',
    name: 'Swet-Ganga Hydropower and Construction  Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 140,
    symbol: 'SGI',
    name: 'Sanima General Insurance Limited',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 278,
    symbol: 'SGIC',
    name: 'Sanima GIC Insurance Limited',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 44,
    symbol: 'SHBL',
    name: 'Sahara Bikas Bank Ltd',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 179,
    symbol: 'SHEL',
    name: 'Singati Hydro Energy Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 39,
    symbol: 'SHINE',
    name: 'Shine Resunga Development Bank Ltd.',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 192,
    symbol: 'SHIVM',
    name: 'SHIVAM CEMENTS LTD',
    sector_id: 8,
    type: 'stock',
  },
  {
    id: 193,
    symbol: 'SHL',
    name: 'Soaltee Hotel Limited',
    sector_id: 4,
    type: 'stock',
  },
  {
    id: 256,
    symbol: 'SHLB',
    name: 'Shrijanshil Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 145,
    symbol: 'SHPC',
    name: 'Sanima Mai Hydropower Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 131,
    symbol: 'SIC',
    name: 'Sagarmatha Insurance Co. Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 135,
    symbol: 'SICL',
    name: 'Shikhar Insurance Co. Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 50,
    symbol: 'SIFC',
    name: 'Shree Investment Finance Co. Ltd.',
    sector_id: 3,
    type: 'stock',
  },
  {
    id: 224,
    symbol: 'SIGS2',
    name: 'Siddhartha Investment Growth Scheme - 2',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 262,
    symbol: 'SIKLES',
    name: 'Sikles Hydropwer limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 136,
    symbol: 'SIL',
    name: 'Siddhartha Insurance Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 41,
    symbol: 'SINDU',
    name: 'Sindhu Bikash Bank Ltd',
    sector_id: 2,
    type: 'stock',
  },
  {
    id: 172,
    symbol: 'SJCL',
    name: 'SANJEN JALAVIDHYUT COMPANY LIMITED',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 279,
    symbol: 'SJLIC',
    name: 'SuryaJyoti Life Insurance Company Limited',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 68,
    symbol: 'SKBBL',
    name: 'Sana Kisan Bikas Bank Ltd',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 67,
    symbol: 'SLBBL',
    name: 'Swarojgar Laghu Bitta Bikas Bank Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 104,
    symbol: 'SLBS',
    name: 'Suryodaya Laghubitta Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 91,
    symbol: 'SLBSL',
    name: 'Samudayik Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 218,
    symbol: 'SLCF',
    name: 'Sanima Large Cap Fund',
    sector_id: 13,
    type: 'stock',
  },
  {
    id: 122,
    symbol: 'SLI',
    name: 'Sanima Life Insurance Limited',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 116,
    symbol: 'SLICL',
    name: 'Surya Life Insurance Company Limited',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 86,
    symbol: 'SMATA',
    name: 'Samata Gharelu Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 88,
    symbol: 'SMB',
    name: 'Support Microfinance Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 95,
    symbol: 'SMFBS',
    name: 'Swabhimaan Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 66,
    symbol: 'SMFDB',
    name: 'Summit Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 269,
    symbol: 'SMH',
    name: 'Super Mai Hydropower Public Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 272,
    symbol: 'SMHL',
    name: 'Super Madi Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 273,
    symbol: 'SMJC',
    name: 'Sagarmatha Jalbidhyut Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 205,
    symbol: 'SPC',
    name: 'Samling Power Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 153,
    symbol: 'SPDL',
    name: 'Synergy Power Development Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 253,
    symbol: 'SPHL',
    name: 'Sayapatri Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 287,
    symbol: 'SPIL',
    name: 'Siddhartha Premier Insurance Limited',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 268,
    symbol: 'SPL',
    name: 'Shuvam Power Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 20,
    symbol: 'SRBL',
    name: 'Sunrise Bank Limited',
    sector_id: 1,
    type: 'stock',
  },
  {
    id: 175,
    symbol: 'SSHL',
    name: 'Shiva Shree Hydropower Ltd',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 199,
    symbol: 'STC',
    name: 'Salt Trading Corporation',
    sector_id: 12,
    type: 'stock',
  },
  {
    id: 63,
    symbol: 'SWBBL',
    name: 'Swabalamban Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 235,
    symbol: 'SWMF',
    name: 'Suryodaya Womi Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 276,
    symbol: 'TAMOR',
    name: 'Sanima Middle Tamor Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 263,
    symbol: 'TJVCL',
    name: 'Trisuli Vidhyut Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 209,
    symbol: 'TPC',
    name: 'Terhathum Power Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 194,
    symbol: 'TRH',
    name: 'Taragaon Regency Hotel Limited',
    sector_id: 4,
    type: 'stock',
  },
  {
    id: 251,
    symbol: 'UHEWA',
    name: 'Upper Hewakhola Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 126,
    symbol: 'UIC',
    name: 'United Insurance Co. (Nepal) Ltd.',
    sector_id: 10,
    type: 'stock',
  },
  {
    id: 238,
    symbol: 'ULBSL',
    name: 'Upakar Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 121,
    symbol: 'ULI',
    name: 'Union Life Insurance Company Limited',
    sector_id: 7,
    type: 'stock',
  },
  {
    id: 154,
    symbol: 'UMHL',
    name: 'United Modi Hydropower Ltd.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 177,
    symbol: 'UMRH',
    name: 'United IDI Mardi RB Hydropower Limited.',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 170,
    symbol: 'UNHPL',
    name: 'Union Hydropower Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 190,
    symbol: 'UNL',
    name: 'Unilever Nepal Limited',
    sector_id: 8,
    type: 'stock',
  },
  {
    id: 285,
    symbol: 'UNLB',
    name: 'Unique Nepal Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 166,
    symbol: 'UPCL',
    name: 'UNIVERSAL POWER COMPANY LTD',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 164,
    symbol: 'UPPER',
    name: 'Upper Tamakoshi Hydropower Ltd',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 246,
    symbol: 'USHEC',
    name: 'Upper Solu Hydro Electric Company Limited',
    sector_id: 5,
    type: 'stock',
  },
  {
    id: 89,
    symbol: 'USLB',
    name: 'Unnati Sahakarya Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 76,
    symbol: 'VLBS',
    name: 'Vijaya laghubitta Bittiya Sanstha Ltd.',
    sector_id: 9,
    type: 'stock',
  },
  {
    id: 260,
    symbol: 'WNLB',
    name: 'WEAN Nepal Laghubitta Bittiya Sanstha Limited',
    sector_id: 9,
    type: 'stock',
  },
];

export { stockSymbolData };
